const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.route('**/auth-config.js*',r=>r.fulfill({contentType:'text/javascript',body:`export const authConfig={url:'https://mock.supabase.co',publishableKey:'public-test'};`}));
await page.route('**/vendor/supabase.js',r=>r.fulfill({contentType:'text/javascript',body:`globalThis.supabase={createClient(){let callback;return {auth:{onAuthStateChange(fn){callback=fn;setTimeout(()=>fn('INITIAL_SESSION',null),0)},async signInWithPassword({email}){callback('SIGNED_IN',{user:{id:email.startsWith('a')?'user-a':'user-b',email},access_token:email.startsWith('a')?'token-a':'token-b'});return {}},async signOut(){callback('SIGNED_OUT',null);return {}},async signUp(){return {}},async resetPasswordForEmail(){return {}},async updateUser(){return {}}}}}};`}));
const rows={};let offline=false;await page.route('https://mock.supabase.co/rest/v1/**',async route=>{if(offline)return route.abort();const req=route.request(),id=req.headers().authorization.replace('Bearer token-','user-');if(req.method()==='GET')return route.fulfill({json:rows[id]?[rows[id]]:[]});const body=req.postDataJSON();if((rows[id]?.revision||0)!==body.expected_revision)return route.fulfill({status:409,json:{code:'40001'}});rows[id]={payload:body.new_payload,revision:body.expected_revision+1};return route.fulfill({json:rows[id].revision});});
await page.goto('http://127.0.0.1:4175/v3/');await page.locator('.splash-screen.is-hidden').waitFor();
async function profile(){await page.locator('[data-view="profile"]').click();await page.locator('[data-account-open]').click();}
async function login(email){await profile();await page.locator('[name="email"]').fill(email);await page.locator('[name="password"]').fill('password123');await page.locator('dialog [type="submit"]').click();await page.waitForFunction(()=>document.querySelector('dialog')?.open===false);await page.waitForTimeout(150);}
async function setRent(value){await page.locator('[data-view="explore"]').click();await page.locator('[data-open-section="housing"]').click();await page.locator('[data-field="rent"]').fill(String(value));}
async function synced(id,value){for(let i=0;i<30;i++){if(rows[id]?.payload.values.rent===value)return;await page.waitForTimeout(100)}throw Error('not synced '+id);}
await login('a@example.com');await setRent(123456);await synced('user-a',123456);
await profile();await page.locator('[data-account-action="logout"]').click();await page.waitForTimeout(100);await login('b@example.com');await setRent(654321);await synced('user-b',654321);assert.equal(rows['user-a'].payload.values.rent,123456);
await profile();await page.locator('[data-account-action="logout"]').click();await page.waitForTimeout(100);await login('a@example.com');await setRent(222222);await synced('user-a',222222);
// Remote revision conflict keeps local changes and refuses overwrite.
rows['user-a'].revision++;rows['user-a'].payload.values.rent=333333;await setRent(444444);await page.waitForTimeout(900);assert.equal(rows['user-a'].payload.values.rent,333333);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('blue-bird-v3-expenses-v1:user-a')).values.rent),444444);
await profile();assert.match(await page.locator('dialog').innerText(),/Otro dispositivo/);await page.locator('[data-account-action="cloud"]').click();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('blue-bird-v3-expenses-v1:user-a')).values.rent),333333);assert.equal(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.includes('backup-conflict')&&JSON.parse(localStorage.getItem(k)).values.rent===444444)),true);await page.locator('.account-close').click();
offline=true;await setRent(555555);await page.waitForTimeout(850);assert.equal(rows['user-a'].payload.values.rent,333333);offline=false;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await synced('user-a',555555);
assert.deepEqual(errors,[]);await browser.close();console.log('PASS mocked Supabase: login/logout, user separation, sync, conflict rejection, backup recovery, offline retry.');})().catch(e=>{console.error(e);process.exit(1)});
